//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFoundation.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAD99
    {
        public int bd_Id { get; set; }
        public string bd_Date { get; set; }
        public Nullable<System.DateTime> bd_Dt { get; set; }
        public string bd_Dr { get; set; }
        public string bd_Cr { get; set; }
        public Nullable<decimal> bd_Amt_Dr { get; set; }
        public Nullable<decimal> bd_Amt_Cr { get; set; }
        public string bd_Narr { get; set; }
        public Nullable<decimal> bd_Balance { get; set; }
        public string bd_Voucher { get; set; }
        public Nullable<int> bd_BId { get; set; }
    }
}
