//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFoundation.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDetail
    {
        public int BID { get; set; }
        public string Bank_Name { get; set; }
        public string Bank_Add { get; set; }
        public string Bank_City { get; set; }
        public string Bank_State { get; set; }
        public string Bank_Acc_no { get; set; }
        public Nullable<decimal> Bank_opening { get; set; }
        public Nullable<decimal> Bank_Closing { get; set; }
        public string Bank_IFSC { get; set; }
        public string Bank_PAN { get; set; }
    }
}
