//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFoundation.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreateStockRaw
    {
        public int Cr_Id { get; set; }
        public string Cr_ProName { get; set; }
        public Nullable<decimal> Cr_MaterialCost { get; set; }
        public Nullable<decimal> Cr_LabourCost { get; set; }
        public Nullable<decimal> Cr_Profit { get; set; }
        public Nullable<decimal> Cr_SaleCost { get; set; }
        public Nullable<int> Cr_Qty { get; set; }
        public Nullable<System.DateTime> Cr_Create_Dt { get; set; }
        public string Cr_Create_User { get; set; }
        public Nullable<System.DateTime> Cr_Modify_Dt { get; set; }
        public string Cr_Modify_User { get; set; }
    }
}
