//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFoundation.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dexp
    {
        public int sno { get; set; }
        public System.DateTime dated { get; set; }
        public string Rema { get; set; }
        public decimal Cost { get; set; }
        public string GItem { get; set; }
        public string dgv { get; set; }
        public Nullable<decimal> exp { get; set; }
    }
}
