//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFoundation.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLPLanding
    {
        public Nullable<int> DLPpid { get; set; }
        public string DLPItemName { get; set; }
        public string DLPType { get; set; }
        public Nullable<double> DLPLanding1 { get; set; }
        public Nullable<double> DLPDlp { get; set; }
        public int Pid { get; set; }
    }
}
