//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFoundation.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmtStockCust
    {
        public int EmtId { get; set; }
        public Nullable<int> EmtCustId { get; set; }
        public string EmtCustName { get; set; }
        public string EmtItemcode { get; set; }
        public string EmtItemsName { get; set; }
        public string EmtType { get; set; }
        public Nullable<double> EmtSend { get; set; }
        public Nullable<double> EmtReceived { get; set; }
        public Nullable<double> EmtBalance { get; set; }
        public Nullable<System.DateTime> EmtDt { get; set; }
    }
}
