//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFoundation.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class fBilling
    {
        public Nullable<int> fbpnid { get; set; }
        public Nullable<int> fbinvno { get; set; }
        public Nullable<System.DateTime> fbbdt { get; set; }
        public string fbbdtv { get; set; }
        public string fbSno { get; set; }
        public string fbmot { get; set; }
        public string fbsize { get; set; }
        public string fbtype { get; set; }
        public string fbWarrVar { get; set; }
        public Nullable<int> fbwarr { get; set; }
        public string fbLanding { get; set; }
        public Nullable<double> fbDlp { get; set; }
        public Nullable<double> fbapb { get; set; }
        public Nullable<double> fbqty { get; set; }
        public Nullable<double> fbStot { get; set; }
        public string fbuser { get; set; }
        public Nullable<System.DateTime> fbucdt { get; set; }
        public string fbmody { get; set; }
        public Nullable<System.DateTime> fbmodydt { get; set; }
        public int fbproid { get; set; }
        public Nullable<double> fbtaxper { get; set; }
        public string fbBatchNo { get; set; }
        public string FbExpDate { get; set; }
        public string FbMRP { get; set; }
        public string fbPreFix { get; set; }
    }
}
