//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFoundation.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fbtot
    {
        public int fbbno { get; set; }
        public string fbdisa { get; set; }
        public Nullable<double> fbdisaa { get; set; }
        public string fbdisb { get; set; }
        public Nullable<double> fbdisba { get; set; }
        public Nullable<double> fbstp { get; set; }
        public Nullable<double> fbsta { get; set; }
        public Nullable<double> fbvatp { get; set; }
        public Nullable<double> fbvata { get; set; }
        public Nullable<double> fbsubt { get; set; }
        public Nullable<double> fbrof { get; set; }
        public Nullable<double> fbgtab { get; set; }
        public string fbono { get; set; }
        public string fbodt { get; set; }
        public string fbtrem { get; set; }
        public Nullable<double> fbBdueold { get; set; }
        public Nullable<double> fbbdwba { get; set; }
        public Nullable<int> fbpch { get; set; }
        public Nullable<System.DateTime> fbbdt { get; set; }
        public Nullable<double> fbtrns { get; set; }
        public Nullable<double> fbDisz { get; set; }
        public Nullable<double> fbDisza { get; set; }
        public string fbtaxyesno { get; set; }
        public Nullable<double> fbetdisa { get; set; }
        public Nullable<double> fbetp { get; set; }
        public Nullable<double> fbetpa { get; set; }
        public string fbPreFix { get; set; }
        public string fbPrescribeBy { get; set; }
    }
}
