//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFoundation.Data.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PBS_TRIALEntities : DbContext
    {
        public PBS_TRIALEntities()
            : base("name=PBS_TRIALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankDetail> BankDetails { get; set; }
        public virtual DbSet<BarcodeStock> BarcodeStocks { get; set; }
        public virtual DbSet<BILLCOST> BILLCOSTs { get; set; }
        public virtual DbSet<Brand_MOT> Brand_MOT { get; set; }
        public virtual DbSet<Dexp> Dexps { get; set; }
        public virtual DbSet<erwcn> erwcns { get; set; }
        public virtual DbSet<eswcn> eswcns { get; set; }
        public virtual DbSet<fParty> fParties { get; set; }
        public virtual DbSet<fPartyPurch> fPartyPurches { get; set; }
        public virtual DbSet<fUser> fUsers { get; set; }
        public virtual DbSet<HSNCode> HSNCodes { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<POS> POS { get; set; }
        public virtual DbSet<pswcn> pswcns { get; set; }
        public virtual DbSet<Sswcn> Sswcns { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<StockEmtOffice> StockEmtOffices { get; set; }
        public virtual DbSet<StockFactory> StockFactories { get; set; }
        public virtual DbSet<StockGodown> StockGodowns { get; set; }
        public virtual DbSet<Temp_wcn> Temp_wcn { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<UQC> UQCs { get; set; }
        public virtual DbSet<Warranty> Warranties { get; set; }
        public virtual DbSet<BAD> BADs { get; set; }
        public virtual DbSet<BAD99> BAD99 { get; set; }
        public virtual DbSet<BADold> BADolds { get; set; }
        public virtual DbSet<CreateStockRaw> CreateStockRaws { get; set; }
        public virtual DbSet<DLPLanding> DLPLandings { get; set; }
        public virtual DbSet<DStock> DStocks { get; set; }
        public virtual DbSet<DStock_CG> DStock_CG { get; set; }
        public virtual DbSet<DStock_MP> DStock_MP { get; set; }
        public virtual DbSet<EmtStockCust> EmtStockCusts { get; set; }
        public virtual DbSet<fBilling> fBillings { get; set; }
        public virtual DbSet<fBilling_bILL> fBilling_bILL { get; set; }
        public virtual DbSet<Fbtot> Fbtots { get; set; }
        public virtual DbSet<Fbtot_bILL> Fbtot_bILL { get; set; }
        public virtual DbSet<Fbtot_temp> Fbtot_temp { get; set; }
        public virtual DbSet<fcuopen> fcuopens { get; set; }
        public virtual DbSet<fcuopen_pur> fcuopen_pur { get; set; }
        public virtual DbSet<fcuopen99> fcuopen99 { get; set; }
        public virtual DbSet<fcuopenold> fcuopenolds { get; set; }
        public virtual DbSet<fcuopenoldPur> fcuopenoldPurs { get; set; }
        public virtual DbSet<fSTVAT> fSTVATs { get; set; }
        public virtual DbSet<ProReturnDetail> ProReturnDetails { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<PurchaseFactory> PurchaseFactories { get; set; }
        public virtual DbSet<PurchaseGODOWN> PurchaseGODOWNs { get; set; }
        public virtual DbSet<PurchaseTaxDtl> PurchaseTaxDtls { get; set; }
        public virtual DbSet<SalReturnDetail> SalReturnDetails { get; set; }
        public virtual DbSet<STOCK_TEMP> STOCK_TEMP { get; set; }
        public virtual DbSet<STOCKDETAILS_EmtPur> STOCKDETAILS_EmtPur { get; set; }
        public virtual DbSet<STOCKDETAILS_EmtSal> STOCKDETAILS_EmtSal { get; set; }
        public virtual DbSet<StockEmtPurchase> StockEmtPurchases { get; set; }
        public virtual DbSet<Product_List> Product_List { get; set; }
        public virtual DbSet<v_BATCH_TALLY> v_BATCH_TALLY { get; set; }
        public virtual DbSet<V_PurchaseRet> V_PurchaseRet { get; set; }
        public virtual DbSet<V_PurRetune> V_PurRetune { get; set; }
        public virtual DbSet<V_Stock> V_Stock { get; set; }
        public virtual DbSet<VCG_Bills> VCG_Bills { get; set; }
        public virtual DbSet<VFindProd> VFindProds { get; set; }
        public virtual DbSet<View_Ftotal_Bill> View_Ftotal_Bill { get; set; }
        public virtual DbSet<VMP_Bills> VMP_Bills { get; set; }
    }
}
