//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFoundation.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseFactory
    {
        public string PName { get; set; }
        public string Addre { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string PMNo { get; set; }
        public Nullable<System.DateTime> pd { get; set; }
        public string Pur_Date { get; set; }
        public string invo { get; set; }
        public string Barcode { get; set; }
        public string item_Name { get; set; }
        public decimal Qty { get; set; }
        public Nullable<decimal> Pur_Cost { get; set; }
        public Nullable<decimal> Tot_Pur { get; set; }
        public string Store { get; set; }
        public string Type { get; set; }
        public int pid { get; set; }
        public Nullable<decimal> cform { get; set; }
        public Nullable<decimal> etax { get; set; }
        public Nullable<decimal> PTax { get; set; }
        public Nullable<decimal> PTaxAmt { get; set; }
        public Nullable<int> pidiNV { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
    }
}
