//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFoundation.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCKDETAILS_EmtSal
    {
        public Nullable<System.DateTime> STDATE { get; set; }
        public string STDATEVAR { get; set; }
        public string STSALETRANVOUCHER { get; set; }
        public string STITEMNAME { get; set; }
        public string STTYPE { get; set; }
        public Nullable<int> STPUR { get; set; }
        public Nullable<int> STSALETRANS { get; set; }
        public Nullable<int> STBALA { get; set; }
        public string STPName { get; set; }
        public Nullable<int> STPid { get; set; }
        public int STid { get; set; }
    }
}
