//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFoundation.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_wcn
    {
        public int CnItId { get; set; }
        public string CnCellNo { get; set; }
        public int CnPn { get; set; }
        public string CnBillno { get; set; }
        public int CnPurid { get; set; }
        public string CnPurBillno { get; set; }
        public Nullable<System.DateTime> CnDate { get; set; }
        public string Store_Place { get; set; }
    }
}
