//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFoundation.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_BATCH_TALLY
    {
        public Nullable<int> fbpnid { get; set; }
        public Nullable<int> fbinvno { get; set; }
        public string fbsize { get; set; }
        public string fbBatchNo { get; set; }
        public string FbExpDate { get; set; }
        public string FbMRP { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
        public string Items { get; set; }
        public string fbPreFix { get; set; }
        public Nullable<System.DateTime> fbbdt { get; set; }
        public Nullable<double> fbqty { get; set; }
    }
}
