//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFoundation.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VFindProd
    {
        public string items { get; set; }
        public decimal cost { get; set; }
        public string group_items { get; set; }
        public string TyreType { get; set; }
        public double Qty { get; set; }
        public string fbBatchNo { get; set; }
        public string FbExpDate { get; set; }
        public string FbMRP { get; set; }
        public string SItems { get; set; }
    }
}
