//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFoundation.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Ftotal_Bill
    {
        public int fbbno { get; set; }
        public Nullable<double> Expr1 { get; set; }
        public string fbPreFix { get; set; }
        public Nullable<System.DateTime> fbbdt { get; set; }
        public Nullable<int> fbtaxbill { get; set; }
    }
}
